### ISSUE TITLE
请问有计划做适配手机端优化吗?

### ISSUE THREAD

**Issue by 125176108** [GmeroAlert/GmAlert#2]
作者你好, 请问有计划做适配手机端优化吗?
我测试过, 手机端允许的效果和电脑一样,  如果优化一下手机端会更好

**Comment by g-mero** [comment]
您希望手机端呈现什么样的效果呢，我们在设计样式的时候对于组件的宽度布局的设计就考虑到了手机端，确保手机端能完整显示组件。在样式细节上并没有将二者进行区分。

你有更加具体的建议，或者有一些推荐的样式参考吗

**Comment by 125176108** [comment]
> 您希望手机端呈现什么样的效果呢，我们在设计样式的时候对于组件的宽度布局的设计就考虑到了手机端，确保手机端能完整显示组件。在样式细节上并没有将二者进行区分。
> 
> 你有更加具体的建议，或者有一些推荐的样式参考吗

比图手机端显示文字偏小, 右上角取消按钮太小
![image](https://github.com/GmeroAlert/GmAlert/assets/157231367/77e83771-592d-49f2-a0d8-41f3e4f51f90)
![1](https://github.com/GmeroAlert/GmAlert/assets/157231367/4f3179d8-a7fd-4cd3-aaf4-4699cfc61d5d)

**Comment by g-mero** [comment]
> > 您希望手机端呈现什么样的效果呢，我们在设计样式的时候对于组件的宽度布局的设计就考虑到了手机端，确保手机端能完整显示组件。在样式细节上并没有将二者进行区分。
> > 你有更加具体的建议，或者有一些推荐的样式参考吗
> 
> 比图手机端显示文字偏小, 右上角取消按钮太小 ![1](https://private-user-images.githubusercontent.com/157231367/298876494-15e9bd20-1dd0-482b-a474-f12725712211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDEzMDYsIm5iZiI6MTcwNjAwMTAwNiwicGF0aCI6Ii8xNTcyMzEzNjcvMjk4ODc2NDk0LTE1ZTliZDIwLTFkZDAtNDgyYi1hNDc0LWYxMjcyNTcxMjIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwOTEwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2YyODBmMjBjOWI5NzIyYzkzNGFmOGNkNDkzOTM2Zjg0M2JjOWQ3NTE5NDlmMGE3OGUxMGY5OTNhMjkwMTI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YhtvAq2BsxKf8pR33CPuCzu5fvyjLPB0ytMJmrNtmuI)

ok，下个主要版本会优化该问题

**Comment by g-mero** [comment]
1.5.0 版本对文字及按钮进行了大小调整和优化
